### ISSUE TITLE
eval/eval.py bug

### ISSUE THREAD

**Issue by kaihsuan** [iii-org/akasha#1]
在使用auto_create_questionset產生問答dataset時出現下列錯誤訊息，使用在local LLM時發生：

\AppData\Local\Programs\Python\Python39\lib\site-packages\akasha\eval\eval.py", line 194, in _save_questionset
    f.write(self.question[w] + self.answer[w] + "\n\n")
IndexError: list index out of range

發現問題出在223行process = "".join(response.split("問題：")).split("答案：")，LLM有時產生的":"不是中文的"："，造成語句無法正確分割，以及第225行應該為"return False"，目前只有"False"。(261行與282行都有一樣的狀況)
![image](https://github.com/iii-org/akasha/assets/11169788/cb5dbb5c-985f-4716-81fd-0fcd40bb5e7e)

**Comment by tea9297** [comment]
Fixed in version 0.8.24
